total_rows = 3

[[rows]]
id = "0"
key = "0"

[rows.value]
name = "Mam conversation 1"
name_es = '"Dieu est bon" chanson'
author = "Madame Rosalie N'Diadan"
link = "https://www.youtube.com/embed/ws16NV4VDEE?si=pXsiVGe94yAkZNJI"

[[rows]]
id = "1"
key = "1"

[rows.value]
name = "Mam conversation 2"
name_es = "Tchagba Dogba Super chanson"
author = "Madame Sidonie Mobio"
link = "https://www.youtube.com/embed/on-h1WJdVog?si=M7Pn3f_dMED5cZZI"

[[rows]]
id = "2"
key = "2"

[rows.value]
name = "Mam conversation 3"
name_es = "Fête des Rameaux chanson"
author = "Madame Léocadie Guébeapo Yapi"
link = "https://www.youtube.com/embed/COiCM6iR_RM"

