total_rows = 13

[[rows]]
id = "0"
key = "0"

[rows.value]
name = '"God is good" song'
name_fr = '"Dieu est bon" chanson'
author = "Madame Rosalie N'Diadan"
link = "https://www.youtube.com/embed/ws16NV4VDEE?si=pXsiVGe94yAkZNJI"

[[rows]]
id = "1"
key = "1"

[rows.value]
name = "Tchagba Dogba Super song"
name_fr = "Tchagba Dogba Super chanson"
author = "Madame Sidonie Mobio"
link = "https://www.youtube.com/embed/on-h1WJdVog?si=M7Pn3f_dMED5cZZI"

[[rows]]
id = "2"
key = "2"

[rows.value]
name = "Palm Sunday song"
name_fr = "Fête des Rameaux chanson"
author = "Madame Léocadie Guébeapo Yapi"
link = "https://www.youtube.com/embed/COiCM6iR_RM"

[[rows]]
id = "3"
key = "3"

[rows.value]
name = "Blessoué Djéhou song"
name_fr = "Blessoué Djéhou chanson"
author = "Madame Adèle Kossike"
link = "https://www.youtube.com/embed/4lyNJMtChto?si=h3l8-5WsdBUaspDX"

[[rows]]
id = "4"
key = "4"

[rows.value]
name = "Áká khúúnbrɛn song"
name_fr = "Áká khúúnbrɛn chanson"
author = "Madame Adèle Kossike"
link = "https://www.youtube.com/embed/8_yJMQUz58g?si=detkB6AKdV-MlTUS"

[[rows]]
id = "5"
key = "5"

[rows.value]
name = "President's house song"
name_fr = "Chanson Chez le président"
author = "Madame Adèle Kossike"
link = "https://www.youtube.com/embed/tuDpuUCPqC8"

[[rows]]
id = "6"
key = "6"

[rows.value]
name = "Félix Houphouêt-Boigny funeral song"
name_fr = "Chanson Félix Houphouët-Boigny"
author = "Madame Evelyne Koutouan"
link = "https://www.youtube.com/embed/4sOlTbSyNms?si=aR0jEEstTqY9uMtT"

[[rows]]
id = "7"
key = "7"

[rows.value]
name = '"Mɛ́n dɛn" song'
name_fr = "Chanson \"J'accepte\""
author = "Henriette N'Diadan"
link = "https://www.youtube.com/embed/KVEqoJXdEP0"

[[rows]]
id = "8"
key = "8"

[rows.value]
name = "Abandoned child story"
name_fr = "L'histoire de l'enfant abandonné"
author = "Madame Félicité Gnaba"
link = "https://www.youtube.com/embed/CwQG9GbVWVE?si=KhBaiOCONQK30cz6"

[[rows]]
id = "9"
key = "9"

[rows.value]
name = "Áyí brɛn song"
name_fr = "Áyí brɛn chanson"
author = "Madame Cynthia N’Diadan"
link = "https://www.youtube.com/embed/AhBHbdQGyjo?si=U_58-XJOl2UVbjCT"

[[rows]]
id = "10"
key = "10"

[rows.value]
name = "N’Cho Norbert song"
name_fr = "N’Cho Norbert chanson"
author = "Madame Adèle Kossike"
link = "https://www.youtube.com/embed/KVvhq1TBMpA?si=_Q0ZDgQOYSQDJJdq"

[[rows]]
id = "11"
key = "11"

[rows.value]
name = "Glory to God song"
name_fr = "Gloire à Dieu chanson"
author = "Madame Adèle Kossike"
link = "https://www.youtube.com/embed/ucdmAiHPD3I?si=0vZ0Miq-0EjsMGGj"
